### ISSUE TITLE
Gui redesign: Replace text labels with buttons

### ISSUE THREAD

**Issue by Brickcaster** [factoriommo/factoriommoscenarios#28]
I'm very partial to the Redmew server GUI design.  Buttons use icons so they don't clutter up the screen.  Button tooltips can provide more information with a simple mouseover.

The buttons in the FMMO tools (information and admin tools) seem a bit verbose and I would like them to be more compact. This also gives more space to add extra functionality, like a player list or Todo list.

Example: 
![image](https://user-images.githubusercontent.com/13324089/36910886-f19852c0-1e0f-11e8-83f5-6d8a6d5a6a07.png)

**Comment by IBlackI** [comment]
Topgui provides the ability to use sprite buttons with a tooltip. I prefer to use the buttons with text because they can be more descriptive. For example the modular_information screen is the first thing that pops up when a user joins. With big red "Close information" it is clear what that button does. With an icon I feel like it isn't immediately as obvious to an user.

I think I will implement this as a possible setting in modular_information and modular_admin.
I will not change the modular_admin and modular_information menu buttons.

**Comment by IBlackI** [comment]
Modular_tag will receive this setting aswell.

**Comment by psihius** [comment]
Closing since implemented
